server:
  port: 0

spring:
  application:
    name: eval-service
  datasource:
    url: jdbc:mysql://inflearndb.c5iaioikw5nv.ap-northeast-2.rds.amazonaws.com
    username: spring
    password: spring12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 3000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  cloud:
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource
    config:
      uri: http://config-service:8888

jwt:
  expiration: 60
  secretKey: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==

  secretKeyRt: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==
  expirationRt: 120

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.203.255.111:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}


logging:
  level:
    root: INFO
    com:
      playdata:
        userservice:
          common: DEBUG
